import React from 'react';

import animate from '../animate.js';

class Code extends React.Component {

	componentDidMount() {
		animate();
	}

	render() {
		return (
			<header id="codeRoot">
				<div className="code">
					<pre>
						&nbsp;1 <span className="storage type">var</span> _react<span className="keyword operator assignment">=</span><span className="variable function">__webpack_require__</span>(<span className="constant numeric">1</span>);<span className="storage type">var</span> _react2<span className="keyword operator assignment">=</span><span className="variable function">_interopRequireDefault</span>(<span className="variable parameter">_react</span>);<span className="variable function">var</span> _reactDom<span className="keyword operator assignment">=</span><br />
						&nbsp;2 <span className="variable function">__webpack_require__</span>(<span className="constant numeric">32</span>);<span className="storage type">var</span> _reactDom2<span className="keyword operator">=</span><span className="variable function">_interopRequireDefault</span>(<span className="variable parameter">_reactDom</span>);<span className="storage type function">function</span> <br />
						&nbsp;3 <span className="variable function">_interopRequireDefault</span>(<span className="variable parameter function">obj</span>{"){"}<span className="keyword control">return</span> {"obj"} <span className="keyword operator assignment">&&</span>obj<span className="keyword operator">.</span><span className="variable other object">__esModule</span><span className="keyword operator ternary">?</span>{"obj:{"}<span className="variable other object">default</span>:<span className="variable other object">obj</span>}};<span className="storage type">var</span> App<span className="keyword operator">=</span><span className="storage type function">function</span><br />
						&nbsp;4 <span className="variable function">App</span>{"(){"}<span className="keyword control">return</span> _react2<span className="keyword operator">.</span>default<span className="keyword operator">.</span><span className="variable function">createElement</span>(<span className="string quoted">'div'</span>,<span className="variable parameter function">null</span>,<span className="string quoted">'calendar'</span>)};<span className="storage type">var</span> rootCalendar<br />
						&nbsp;5 <span className="keyword operator">=</span>document<span className="keyword operator">.</span><span className="variable function">getElementById</span>(<span className="string quoted">'rootCalendar'</span>);_reactDom2<span className="keyword operator">.</span>default<span className="keyword operator">.</span><span className="variable function">render</span>(<span className="variable parameter">_react2</span><span className="keyword operator">.</span>default<br />
						&nbsp;6 <span className="keyword operator">.</span><span className="variable function">createElement</span>(<span className="variable parameter">App</span>,<span className="variable parameter">null</span>),<span className="variable parameter">rootCalendar</span>)},<span className="storage type function">function</span>(<span className="variable parameter function">module</span>,<span className="variable parameter function">exports</span>,<span className="variable parameter function">__webpack_require__</span>){"{"}<br />
						&nbsp;7 <span className="string quoted">'use strict'</span>;module<span className="keyword operator assignment">.</span><span className="support type">exports</span><span className="keyword operator assignment">=</span><span className="variable function">__webpack_require__</span>(<span className="constant numeric">2</span>)},<br />
						&nbsp;8 <span className="storage type function">function</span>(<span className="variable parameter">module</span>, <span className="variable parameter">exports</span>,<span className="variable parameter">__webpack_require__</span>{"){("}<span className="storage type function">function</span>(<span className="variable parameter function">process</span>{"){"}<span className="string quoted">'use strict'</span>;<span className="storage type">var</span> _assign<span className="keyword operator assignment">=</span><br />
						&nbsp;9 <span className="variable function">__webpack_require__</span>(<span className="constant numeric">4</span>);<span className="storage type">var</span> <span className="variable other readwrite">ReactChildren</span>=<span className="variable function">__webpack_require__</span>(<span className="constant numeric">5</span>);<span className="storage type">var</span> <span className="variable other object">ReactComponent</span><span className="keyword operator assignment">=</span><br />
						10 <span className="variable function">__webpack_require__</span>(<span className="constant numeric">18</span>);<span className="storage type">var</span> ReactPureComponent<span className="keyword operator">=</span><span className="variable function">__webpack_require__</span>(<span className="constant numeric">21</span>);<span className="storage type">var</span> ReactClass<span className="keyword operator assignment">=</span><br />
						11 <span className="variable function">__webpack_require__</span>(<span className="constant numeric">22</span>);<span className="storage type">var</span><span className="variable other readwrite">ReactDOMFactories</span><span className="keyword operator assignment">=</span><span className="variable function">__webpack_require__</span>(<span className="constant numeric">24</span>);<span className="storage type">var</span> ReactElement<span className="keyword operator assignment">=</span><br />
						12 <span className="variable function">__webpack_require__</span>(<span className="constant numeric">9</span>);<span className="storage type=">var</span> ReactPropTypes<span className="keyword operator assignment">=</span>__webpack_require__(<span className="constant numeric">29</span>);<span className="storage type">var</span> ReactVersion<span className="keyword operator assignment">=</span><br />
						13 <span className="variable function">__webpack_require__</span>(<span className="constant numeric">30</span>);<span className="keyword control">var</span> <span className="variable other readwrite">onlyChild</span><span className="keyword operator assignment">=</span><span className="variable function">__webpack_require__</span>(<span className="constant numeric">31</span>);<span className="storage type">var</span> warning<span className="keyword operator assignment">=</span><br />
						14 <span className="variable function">__webpack_require__</span>(<span className="constant numeric">11</span>);<span className="storage type">var</span> createElement<span className="keyword operator assignment">=</span>ReactElement<span className="keyword operator">.</span><span className="variable other object">createElement</span>;<span className="storage type">var</span> <span className="variable other object">createFactory</span><span className="keyword operator">=</span><br />
						15 ReactElement<span className="keyword operator">.</span>createFactory;<span className="storage type">var</span> <span className="variable other readwrite">cloneElement</span>=ReactElement<span className="keyword operator">.</span><span className="variable other object">cloneElement</span>;<span className="keyword control conditional">if</span>(process<span className="keyword operator">.</span>env<br />
						16 <span className="keyword operator">.</span>NODE_ENV<span className="keyword operator">!==</span><span className="string quoted">'production'</span>{"){"}<span className="type storage">var</span> ReactElementValidator<span className="keyword operator">=</span><span className="variable function">__webpack_require__</span>(<span className="constant numeric">25</span>);createElement<span className="keyword operator assignment">=</span><br />
						17 ReactElementValidator<span className="keyword operator">.</span><span className="variable other readwrite">createElement</span>;createFactory<span className="keyword operator">=</span>ReactElementValidator<span className="keyword operator">.</span>createFactory;<br />
						18 <span className="variable other object">cloneElement</span><span className="keyword operator assignment">=</span>ReactElementValidator<span className="keyword opreator">.</span><span className="variable other object">cloneElement</span>};<span className="storage type">var</span> __spread<span className="keyword operator">=</span>_assign;<span className="keyword control conditional">if</span>(process<span className="keyword operator">.</span>env<br />
					</pre>
				</div>
			</header>
		);
	}

}

export default Code;